#Koristimo stabilnu bazu s PyTorchom i CUDA podrškom
FROM pytorch/pytorch:2.1.2-cuda12.1-cudnn8-runtime

#Postavljamo radni direktorij unutar kontejnera
WORKDIR /workdir

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Etc/UTC
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

#Instalacija sistemskih biblioteka potrebnih za OpenCV i rad sa slikama
RUN apt-get update && apt-get install -y \
    git \
    wget \
    curl \
    nano \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender1 \
    libgl1-mesa-glx \
    && rm -rf /var/lib/apt/lists/*

#Instalacija Python paketa s fiksnom verzijom numpy-ja radi kompatibilnosti
RUN pip install --no-cache-dir \
    numpy==1.26.4 \
    scipy \
    scikit-image \
    matplotlib \
    pandas \
    tqdm \
    nibabel \
    SimpleITK \
    opencv-python \
    pyyaml \
    scikit-learn


#Instalacija nnU-Net v2 i alata za skeletizaciju/topologiju
RUN pip install --no-cache-dir \
    nnunetv2

    # 3. Nastavitev okoljskih spremenljivk za nnU-Net v2
ENV nnUNet_raw="/workdir/data/nnUNet_raw"
ENV nnUNet_preprocessed="/workdir/data/nnUNet_preprocessed"
ENV nnUNet_results="/workdir/code/nnUNet_results_new"

# Vrnitev v korensko mapo repozitorija za lažji zagon skript
WORKDIR /workdir